
"use client"
import React, { useEffect } from 'react'

const Imprint = () => {

  useEffect(() => {
    setTimeout(() => {
      window.scrollTo({ top: 0, behavior: "smooth" });
    }, 0);
  }, []);

  return (
    <>
      <section className="global_wrapper terms_wrapper">
        <div className="container mt-4">
          <div className="terms_wrapper__content">
            <h3>Datenschutzerklärung</h3>
            <div className="terms_list">
              <h6><span>1</span> Information über die Erhebung personenbezogener Daten und Kontaktdaten des Verantwortlichen</h6>
              <h6><span>1.1</span>  Wir freuen uns, dass Sie unsere Website besuchen und bedanken uns für Ihr Interesse. Im Folgenden informieren wir Sie über den Umgang mit Ihren personenbezogenen Daten bei der Nutzung unserer Website. Personenbezogene Daten sind hierbei alle Daten, mit denen Sie persönlich identifiziert werden können.</h6>
              <h6><span>1.2</span>  Verantwortlicher für die Datenverarbeitung auf dieser Website im Sinne der Datenschutz-Grundverordnung (DSGVO) ist:</h6>
              <p> Emanuel Wintermeyer Herbartstraße 12</p>
              <p>Turiya Yoga</p>
              <p>60316 Frankfurt am Main, Germany</p>
              <div className="terms_link">
                <a href="tel:+ 49 (0) 69 – 2013 4987">Telefon: + 49 (0) 69 – 2013 4987</a>
                <a href="mailto:info@turiyayoga.de">E-Mail: info@turiyayoga.de</a>
              </div>
              <p>Der für die Verarbeitung von personenbezogenen Daten Verantwortliche ist diejenige natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet.</p>
              <p><span>1.3</span>          Diese Website nutzt aus Sicherheitsgründen und zum Schutz der Übertragung personenbezogener Daten und anderer vertraulicher Inhalte (z.B. Bestellungen oder Anfragen an den Verantwortlichen) eine SSL-bzw. TLS-Verschlüsselung. Sie können eine verschlüsselte Verbindung an der Zeichenfolge „https://“ und dem Schloss-Symbol in Ihrer Browserzeile erkennen.</p>
              <h6><span>2</span> Datenerfassung beim Besuch unserer Website</h6>
              <p>Bei der bloß informatorischen Nutzung unserer Website, also wenn Sie sich nicht registrieren oder uns anderweitig Informationen übermitteln, erheben wir nur solche Daten, die Ihr Browser an unseren Server übermittelt (sog. „Server-Logfiles“). Wenn Sie unsere Website aufrufen, erheben wir die folgenden Daten, die für uns technisch erforderlich sind, um Ihnen die Website anzuzeigen:</p>
              <p>Unsere besuchte Website</p>
              <p>  Datum und Uhrzeit zum Zeitpunkt des Zugriffes</p>
              <p>  Menge der gesendeten Daten in Byte</p>
              <p>Quelle/Verweis, von welchem Sie auf die Seite gelangten</p>
              <p>Verwendeter Browser</p>
              <p> Verwendetes Betriebssystem</p>
              <p>Verwendete IP-Adresse (ggf.: in anonymisierter Form)</p>
              <p>Die Verarbeitung erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an der Verbesserung der Stabilität und Funktionalität unserer Website. Eine Weitergabe oder anderweitige Verwendung der Daten findet nicht statt. Wir behalten uns allerdings vor, die Server-Logfiles nachträglich zu überprüfen, sollten konkrete Anhaltspunkte auf eine rechtswidrige Nutzung hinweisen.</p>
              <h6><span>3</span> Hosting</h6>
              <p>Wir nutzen den Domain-Registrierungs- und Webhosting-Diensteanbieter: Hostinger International, Ltd., 61 Lordou Vironos Street, 6023 Larnaca, Zypern („Hostinger“) zum Zwecke des Hostings und der Darstellung der Seiteninhalte auf Basis einer Verarbeitung in unserem Auftrag. Sämtliche auf unserer Website erhobenen Daten werden auf den Servern von Hostinger verarbeitet. Im Rahmen der vorgenannten Leistungen von Hostinger können Daten auch im Rahmen einer weiteren Verarbeitung im Auftrag an Server von Hostinger in anderen Ländern übermittelt werden. Wir haben mit Hostinger einen Auftragsverarbeitungsvertrag abgeschlossen, mit dem Hostinger verpflichtet wird, die Daten unserer Seitenbesucher zu schützen und sie nicht an Dritte weiterzugeben. Für die Übermittlung von Daten aus der EU in andere Länder beruft sich Hostinger hierbei auf sog. Standarddatenschutzklauseln der Europäischen Kommission, welche die Einhaltung des europäischen Datenschutzniveaus in diesen Ländern gewährleisten sollen.
                Weitere Hinweise zum Datenschutz von Hostinger erhalten Sie unter der nachstehenden Website: https://www.hostinger.de; und Datenschutzerklärung: https://www.hostinger.de/datenschutzrichtlinie.
                Eine weitere Verarbeitung auf anderen Servern als den vorgenannten von Hostinger findet nur im nachstehend mitgeteilten Rahmen statt.</p>
              <h6><span>4</span> Cookies</h6>
              <p>Um den Besuch unserer Website attraktiv zu gestalten und die Nutzung bestimmter Funktionen zu ermöglichen, verwenden wir auf verschiedenen Seiten sogenannte Cookies. Hierbei handelt es sich um kleine Textdateien, die auf Ihrem Endgerät abgelegt werden. Einige der von uns verwendeten Cookies werden nach dem Ende der Browser-Sitzung, also nach Schließen Ihres Browsers, wieder gelöscht (sog. Sitzungs-Cookies). Andere Cookies verbleiben auf Ihrem Endgerät und ermöglichen uns oder unseren Partnerunternehmen (Cookies von Drittanbietern), Ihren Browser beim nächsten Besuch wiederzuerkennen (persistente Cookies). Werden Cookies gesetzt, erheben und verarbeiten diese im individuellen Umfang bestimmte Nutzerinformationen wie Browser- und Standortdaten sowie IP-Adresswerte. Persistente Cookies werden automatisiert nach einer vorgegebenen Dauer gelöscht, die sich je nach Cookie unterscheiden kann.</p>
              <p>Sofern durch einzelne von uns implementierte Cookies auch personenbezogene Daten verarbeitet werden, erfolgt die Verarbeitung gemäß Art. 6 Abs. 1 lit. b DSGVO entweder zur Durchführung des Vertrages oder gemäß Art. 6 Abs. 1 lit. f DSGVO zur Wahrung unserer berechtigten Interessen an der bestmöglichen Funktionalität der Website sowie einer kundenfreundlichen und effektiven Ausgestaltung des Seitenbesuchs.</p>
              <p>Wir arbeiten unter Umständen mit Werbepartnern zusammen, die uns helfen, unser Internetangebot für Sie interessanter zu gestalten. Zu diesem Zweck werden für diesen Fall bei Ihrem Besuch unserer Website auch Cookies von Partnerunternehmen auf Ihrer Festplatte gespeichert (Cookies von Drittanbietern). Wenn wir mit vorbenannten Werbepartnern zusammenarbeiten, werden Sie über den Einsatz derartiger Cookies und den Umfang der jeweils erhobenen Informationen innerhalb der nachstehenden Absätze individuell und gesondert informiert.</p>
              <p>Bitte beachten Sie, dass Sie Ihren Browser so einstellen können, dass Sie über das Setzen von Cookies informiert werden und einzeln über deren Annahme entscheiden oder die Annahme von Cookies für bestimmte Fälle oder generell ausschließen können. Jeder Browser unterscheidet sich in der Art, wie er die Cookie-Einstellungen verwaltet. Diese ist in dem Hilfemenü jedes Browsers beschrieben, welches Ihnen erläutert, wie Sie Ihre Cookie-Einstellungen ändern können. Diese finden Sie für die jeweiligen Browser unter den folgenden Links:</p>
              <p>Internet Explorer: <a href="http://windows.microsoft.com/de-DE/windows-vista/Block-or-allow-cookies">http://windows.microsoft.com/de-DE/windows-vista/Block-or-allow-cookies</a></p>
              <p>Firefox: <a href="https://support.mozilla.org/de/kb/cookies-erlauben-und-ablehnen">https://support.mozilla.org/de/kb/cookies-erlauben-und-ablehnen</a></p>
              <p>Chrome: <a href="http://support.google.com/chrome/bin/answer.py?hl=de&hlrm=en&answer=95647">http://support.google.com/chrome/bin/answer.py?hl=de&amp;hlrm=en&amp;answer=95647</a></p>
              <p>Safari: <a href=" https://support.apple.com/de-de/guide/safari/sfri11471/mac"> https://support.apple.com/de-de/guide/safari/sfri11471/mac</a></p>
              <p>Opera: <a href="http://help.opera.com/Windows/10.20/de/cookies.html">http://help.opera.com/Windows/10.20/de/cookies.html</a></p>
              <p>Bitte beachten Sie, dass bei Nichtannahme von Cookies die Funktionalität unserer Website eingeschränkt sein kann.</p>
              <h6><span>5</span> Kontaktaufnahme</h6>
              <p>Im Rahmen der Kontaktaufnahme mit uns (z.B. per Kontaktformular oder E-Mail) werden personenbezogene Daten erhoben. Welche Daten im Falle der Nutzung eines Kontaktformulars erhoben werden, ist aus dem jeweiligen Kontaktformular ersichtlich. Diese Daten werden ausschließlich zum Zweck der Beantwortung Ihres Anliegens bzw. für die Kontaktaufnahme und die damit verbundene technische Administration gespeichert und verwendet. Rechtsgrundlage für die Verarbeitung dieser Daten ist unser berechtigtes Interesse an der Beantwortung Ihres Anliegens gemäß Art. 6 Abs. 1 lit. f DSGVO. Zielt Ihre Kontaktierung auf den Abschluss eines Vertrages ab, so ist zusätzliche Rechtsgrundlage für die Verarbeitung Art. 6 Abs. 1 lit. b DSGVO. Ihre Daten werden nach abschließender Bearbeitung Ihrer Anfrage gelöscht. Dies ist der Fall, wenn sich aus den Umständen entnehmen lässt, dass der betroffene Sachverhalt abschließend geklärt ist und sofern keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p>
              <h6><span>6</span> Registrierung</h6>
              <p>Sie können sich auf unserer Website unter Angabe von personenbezogenen Daten registrieren. Welche personenbezogenen Daten für die Registrierung verarbeitet werden, ergibt sich aus der Eingabemaske, die für die Registrierung verwendet wird. Wir verwenden für die Registrierung das sog. Double-opt-in-Verfahren, d. h. Ihre Registrierung ist erst abgeschlossen, wenn Sie zuvor Ihre Anmeldung über eine Ihnen zu diesem Zweck zugesandte Bestätigungs-E-Mail durch Klick auf den darin enthaltenem Link bestätigt haben. Falls Ihre diesbezügliche Bestätigung nicht binnen 24 Stunden erfolgt, wird Ihre Anmeldung automatisch aus unserer Datenbank gelöscht. Die Angabe der zuvor genannten Daten ist verpflichtend. Alle weiteren Informationen können Sie freiwillig durch Nutzung unseres Portals bereitstellen.</p>
              <p>Wenn Sie unser Portal nutzen, speichern wir Ihre zur Vertragserfüllung erforderlichen Daten, auch evtl. Angaben zur Zahlungsweise, bis Sie Ihren Zugang endgültig löschen. Weiterhin speichern wir die von Ihnen angegebenen freiwilligen Daten für die Zeit Ihrer Nutzung des Portals, soweit Sie diese nicht zuvor löschen. Alle Angaben können Sie im geschützten Kundenbereich verwalten und ändern. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.</p>
              <p>Darüber hinaus speichern wir alle von Ihnen veröffentlichten Inhalte (wie z.B. öffentliche Beiträge, Pinnwandeinträge, Gästebucheintragungen, etc.), um die Website zu betreiben. Wir haben ein berechtigtes Interesse an der Bereitstellung der Website mit dem vollständigen User-Generated-Content. Die Rechtsgrundlage hierfür ist Art. 6 Abs. 1 lit. f DSGVO. Wenn Sie Ihren Account löschen, bleiben Ihre öffentlichen Äußerungen, insbesondere im Forum, weiterhin für alle Leser sichtbar, Ihr Account ist jedoch nicht mehr abrufbar. Alle übrigen Daten werden in diesem Fall gelöscht.</p>
              <h6><span>7</span> Nutzung von Kundendaten zur Direktwerbung</h6>
              <h6><span>7.1</span> Anmeldung zu unserem E-Mail-Newsletter</h6>
              <p>Wenn Sie sich zu unserem E-Mail Newsletter anmelden, übersenden wir Ihnen regelmäßig Informationen zu unseren Angeboten. Pflichtangabe für die Übersendung des Newsletters ist allein Ihre E-Mailadresse. Die Angabe weiterer Daten ist freiwillig und wird verwendet, um Sie persönlich ansprechen zu können. Für den Versand des Newsletters verwenden wir das sog. Double Opt-in Verfahren. Dies bedeutet, dass wir Ihnen erst dann einen E-Mail Newsletter übermitteln werden, wenn Sie uns ausdrücklich bestätigt haben, dass Sie in den Empfang von Newsletter einwilligen. Wir schicken Ihnen dann eine Bestätigungs-E-Mail, mit der Sie gebeten werden durch Anklicken eines entsprechenden Links zu bestätigen, dass Sie künftig den Newsletter erhalten wollen.</p>
              <p>Mit der Aktivierung des Bestätigungslinks erteilen Sie uns Ihre Einwilligung für die Nutzung Ihrer personenbezogenen Daten gemäß Art. 6 Abs. 1 lit. a DSGVO. Bei der Anmeldung zum Newsletter speichern wir Ihre vom Internet Service-Provider (ISP) eingetragene IP-Adresse sowie das Datum und die Uhrzeit der Anmeldung, um einen möglichen Missbrauch Ihrer E-Mail- Adresse zu einem späteren Zeitpunkt nachvollziehen zu können. Die von uns bei der Anmeldung zum Newsletter erhobenen Daten werden ausschließlich für Zwecke der werblichen Ansprache im Wege des Newsletters benutzt. Sie können den Newsletter jederzeit über den dafür vorgesehenen Link im Newsletter oder durch entsprechende Nachricht an den eingangs genannten Verantwortlichen abbestellen. Nach erfolgter Abmeldung wird Ihre E-Mailadresse unverzüglich in unserem Newsletter-Verteiler gelöscht, soweit Sie nicht ausdrücklich in eine weitere Nutzung Ihrer Daten eingewilligt haben oder wir uns eine darüber hinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und über die wir Sie in dieser Erklärung informieren.</p>
              <h6><span>7.2</span> Newsletter-Versand via Mailjet</h6>
              <p>Der Versand unserer E-Mail-Newsletter erfolgt über den technischen Dienstleister Mailjet (Mailjet GmbH, c/o Workrepublic, Berliner Allee 26, 40212 Düsseldorf), an den wir Ihre bei der Newsletteranmeldung bereitgestellten Daten weitergeben. Diese Weitergabe erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO und dient unserem berechtigten Interesse an der Verwendung eines werbewirksamen, sicheren und nutzerfreundlichen Newslettersystems. Die von Ihnen zwecks Newsletterbezugs eingegebenen Daten (z.B. E-Mail-Adresse) werden auf den Servern von Mailjet in der EU gespeichert.</p>
              <p>Mailjet verwendet diese Informationen zum Versand und zur statistischen Auswertung der Newsletter in unserem Auftrag. Für die Auswertung beinhalten die versendeten E-Mails sog. Web-Beacons bzw. Trackings-Pixel, die Ein-Pixel-Bilddateien darstellen, die auf unserer Website gespeichert sind. So kann festgestellt werden, ob eine Newsletter-Nachricht geöffnet und welche Links ggf. angeklickt wurden. Außerdem werden technische Informationen erfasst (z.B. Zeitpunkt des Abrufs, IP-Adresse, Browsertyp und Betriebssystem). Die Daten werden ausschließlich pseudonymisiert erhoben und werden nicht mit Ihren weiteren persönlichen Daten verknüpft, eine direkte Personenbeziehbarkeit wird ausgeschlossen. Diese Daten dienen ausschließlich der statistischen Analyse von Newsletterkampagnen. Die Ergebnisse dieser Analysen können genutzt werden, um künftige Newsletter besser an die Interessen der Empfänger anzupassen. Wenn Sie der Datenanalyse zu statistischen Auswertungszwecken widersprechen möchten, müssen Sie den Newsletterbezug abbestellen.</p>
              <p>Des Weiteren kann Mailjet diese Daten gemäß Art. 6 Abs. 1 lit. f DSGVO selbst aufgrund seines eigenen berechtigten Interesses an der bedarfsgerechten Ausgestaltung und der Optimierung des Dienstes sowie zu Marktforschungszwecken nutzen, um etwa zu bestimmen, aus welchen Ländern die Empfänger kommen. Mailjet nutzt die Daten unserer Newsletterempfänger jedoch nicht, um diese selbst anzuschreiben oder sie an Dritte weiterzugeben.</p>
              <p>Wir haben mit Mailjet einen Auftragsverarbeitungsvertrag abgeschlossen, mit dem wir Mailjet verpflichten, die Daten unserer Kunden zu schützen und sie nicht an Dritte weiterzugeben.</p>
              <p>Die Datenschutzbestimmungen von Mailjet können Sie hier einsehen: <a href="https://www.mailjet.de/privacy-policy/">https://www.mailjet.de/privacy-policy/</a></p>
              <h6><span>7.3</span> Werbung per Briefpost</h6>
              <p>Auf Grundlage unseres berechtigten Interesses an personalisierter Direktwerbung behalten wir uns vor, Ihren Vor- und Nachnamen, Ihre Postanschrift und - soweit wir diese zusätzlichen Angaben im Rahmen der Vertragsbeziehung von Ihnen erhalten haben - Ihren Titel, akademischen Grad, Ihr Geburtsjahr und Ihre Berufs-, Branchen- oder Geschäftsbezeichnung gemäß Art. 6 Abs. 1 lit. f DSGVO zu speichern und für die Zusendung von interessanten Angeboten und Informationen zu unseren Produkten per Briefpost zu nutzen.</p>
              <p>Sie können der Speicherung und Nutzung Ihrer Daten zu diesem Zweck jederzeit durch eine entsprechende Nachricht an den Verantwortlichen widersprechen.</p>
              <h6><span>8</span>  Verwendung von Sozialen Medien: Social Plugins</h6>
              <h6><span>8.1</span>    Facebook-Plugins mit Shariff-Lösung</h6>
              <p>Auf unserer Website werden sogenannte Social Plugins ("Plugins") des sozialen Netzwerkes Facebook verwendet, das von der Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland ("Facebook") betrieben wird.</p>
              <p>Um den Schutz Ihrer Daten beim Besuch unserer Website zu erhöhen, sind diese Schaltflächen nicht uneingeschränkt als Plugins, sondern lediglich unter Verwendung eines HTML-Links in die Seite eingebunden. Durch diese Art der Einbindung wird gewährleistet, dass beim Aufruf einer Seite unserer Website, die solche Schaltflächen enthält, noch keine Verbindung mit den Servern von Facebook hergestellt wird. Wenn Sie auf die Schaltfläche klicken, öffnet sich ein neues Browserfenster und ruft die Seite von Facebook auf, auf der Sie (ggf. nach Eingabe Ihrer Login-Daten) mit den dortigen Plugins interagieren können.</p>
              <p>Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch Facebook sowie Ihre diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz Ihrer Privatsphäre entnehmen Sie bitte den Datenschutzhinweisen von Facebook: <a href="https://www.facebook.com/policy.php">https://www.facebook.com/policy.php/</a></p>
              <h6><span>8.2</span>  Instagram-Plugin als Shariff-Lösung</h6>
              <p>Auf unserer Website werden sogenannte Social Plugins („Plugins“) des Online-Dienstes Instagram verwendet, das von der Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2 Ireland („Facebook“) betrieben wird.</p>
              <p>Um den Schutz Ihrer Daten beim Besuch unserer Website zu erhöhen, sind diese Schaltflächen nicht uneingeschränkt als Plugins, sondern lediglich unter Verwendung eines HTML-Links in die Seite eingebunden. Durch diese Art der Einbindung wird gewährleistet, dass beim Aufruf einer Seite unserer Website, die solche Schaltflächen enthält, noch keine Verbindung mit den Servern von Instagram hergestellt wird. Wenn Sie auf die Schaltfläche klicken, öffnet sich ein neues Browserfenster und ruft die Seite von Instagram auf, auf der Sie (ggf. nach Eingabe Ihrer Login-Daten) mit den dortigen Plugins interagieren können.</p>
              <p>Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch Instagram sowie Ihre diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz Ihrer Privatsphäre entnehmen Sie bitte den Datenschutzhinweisen von Instagram: <a href="https://help.instagram.com/155833707900388/">https://help.instagram.com/155833707900388/</a></p>
              <h6><span>8.3</span> LinkedIn-Plugin als Shariff-Lösung</h6>
              <p>Auf unserer Website werden sogenannte Social Plugins („Plugins“) des Online-Dienstes LinkedIn verwendet, das von der LinkedIn Ireland Unlimited Company, Wilton Place, Dublin 2, Irland (“LinkedIn”) betrieben wird.</p>
              <p>Um den Schutz Ihrer Daten beim Besuch unserer Website zu erhöhen, sind diese Schaltflächen nicht uneingeschränkt als Plugins, sondern lediglich unter Verwendung eines HTML-Links in die Seite eingebunden. Durch diese Art der Einbindung wird gewährleistet, dass beim Aufruf einer Seite unserer Website, die solche Schaltflächen enthält, noch keine Verbindung mit den Servern von LinkedIn hergestellt wird. Wenn Sie auf die Schaltfläche klicken, öffnet sich ein neues Browserfenster und ruft die Seite von LinkedIn auf, auf der Sie (ggf. nach Eingabe Ihrer Login-Daten) mit den dortigen Plugins interagieren können.</p>
              <p>Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch LinkedIn sowie Ihre diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz Ihrer Privatsphäre entnehmen Sie bitte den Datenschutzhinweisen von LinkedIn: <a href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a></p>
              <h6><span>8.4</span>Twitter-Plugin als Shariff-Lösung</h6>
              <p>Auf unserer Website werden sogenannte Social Plugins ("Plugins") des Mikroblogging-Dienstes Twitter verwendet, der von der Twitter International Company, One Cumberland Place, Fenian Street
                Dublin 2, D02 AX07 Irland ("Twitter") betrieben wird.</p>
              <p>Um den Schutz Ihrer Daten beim Besuch unserer Website zu erhöhen, sind diese Schaltflächen nicht uneingeschränkt als Plugins, sondern lediglich unter Verwendung eines HTML-Links in die Seite eingebunden. Durch diese Art der Einbindung wird gewährleistet, dass beim Aufruf einer Seite unserer Website, die solche Schaltflächen enthält, noch keine Verbindung mit den Servern von Twitter hergestellt wird. Wenn Sie auf die Schaltfläche klicken, öffnet sich ein neues Browserfenster und ruft die Seite von Twitter auf, auf der Sie (ggf. nach Eingabe Ihrer Login-Daten) mit den dortigen Plugins interagieren können. Bitte beachten Sie, dass bei Interaktion mit dem Plugin erhobene Informationen (einschließlich Ihrer IP-Adresse) von Ihrem Browser direkt an einen Server von Twitter Inc. in die USA übermittelt und dort gespeichert werden.</p>
              <p>Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch Twitter sowie Ihre diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz Ihrer Privatsphäre entnehmen Sie bitte den Datenschutzhinweisen von Twitter: <a href="https://twitter.com/privacy">https://twitter.com/privacy</a></p>
              <h6><span>9</span> Verwendung von Sozialen Medien: Videos</h6>
              <h6>Verwendung von Youtube-Videos</h6>
              <p>Diese Website nutzt die Youtube-Einbettungsfunktion zur Anzeige und Wiedergabe von Videos des Anbieters „Youtube“, der zu der Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland („Google“) gehört.</p>
              <p>Hierbei wird der erweiterte Datenschutzmodus verwendet, der nach Anbieterangaben eine Speicherung von Nutzerinformationen erst bei Wiedergabe des/der Videos in Gang setzt. Wird die Wiedergabe eingebetteter Youtube-Videos gestartet, setzt der Anbieter „Youtube“ Cookies ein, um Informationen über das Nutzerverhalten zu sammeln. Hinweisen von „Youtube“ zufolge dienen diese unter anderem dazu, Videostatistiken zu erfassen, die Nutzerfreundlichkeit zu verbessern und missbräuchliche Handlungsweisen zu unterbinden. Wenn Sie bei Google eingeloggt sind, werden Ihre Daten direkt Ihrem Konto zugeordnet, wenn Sie ein Video anklicken. Wenn Sie die Zuordnung mit Ihrem Profil bei YouTube nicht wünschen, müssen Sie sich vor Aktivierung des Buttons ausloggen. Google speichert Ihre Daten (selbst für nicht eingeloggte Nutzer) als Nutzungsprofile und wertet diese aus. Eine solche Auswertung erfolgt insbesondere gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis der berechtigten Interessen von Google an der Einblendung personalisierter Werbung, Marktforschung und/oder bedarfsgerechten Gestaltung seiner Website. Ihnen steht ein Widerspruchsrecht zu gegen die Bildung dieser Nutzerprofile, wobei Sie sich zur Ausübung dessen an YouTube richten müssen. Im Rahmen der Nutzung von Youtube kann es auch zu einer Übermittlung von personenbezogenen Daten an die Server der Google LLC. in den USA kommen.</p>
              <p>Unabhängig von einer Wiedergabe der eingebetteten Videos wird bei jedem Aufruf dieser Website eine Verbindung zum Google-Netzwerk aufgenommen, was ohne unseren Einfluss weitere Datenverarbeitungsvorgänge auslösen kann.</p>
              <p>Weitere Informationen zum Datenschutz bei „Youtube“ finden Sie in den Youtube-Nutzungsbedingungen unter https://www.youtube.com/static?template=terms sowie in der Datenschutzerklärung von Google unter https://www.google.de/intl/de/policies/privacy.</p>
              <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, deaktivieren Sie diesen Dienst im auf der Webseite bereitgestellten "Cookie-Consent-Tool".</p>
              <h6><span>10</span> Online-Marketing</h6>
              <h6><span>10.1</span>  Google AdSense</h6>
              <p>Diese Website benutzt Google AdSense, einen Webanzeigendienst Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland ("Google"). Google AdSense verwendet sog. Cookies sind Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Darüber hinaus verwendet Google AdSense zur Sammlung von Informationen auch sog. "Web-Beacons" (kleine unsichtbare Grafiken), durch deren Verwendung einfache Aktionen wie der Besucherverkehr auf der Website aufgezeichnet, gesammelt und ausgewertet werden können. Die durch das Cookie und/ oder Web-Beacon erzeugten Informationen (einschließlich Ihrer IP-Adresse) über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google übertragen und dort gespeichert. Hierbei kann es auch zu einer Übermittlung an die Server der Google LLC. in den USA kommen.</p>
              <p>Google benutzt die so erhaltenen Informationen, um eine Auswertung Ihres Nutzungsverhaltens im Hinblick auf die AdSense-Anzeigen durchzuführen. Die im Rahmen von Google AdSense von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Die von Google erhobenen Informationen werden unter Umständen an Dritte übertragen, sofern dies gesetzlich vorgeschrieben ist und/ oder soweit Dritte diese Daten im Auftrag von Google verarbeiten.</p>
              <p>Die beschriebene Verarbeitung von Daten erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO zum Zweck der zielgerichteten werblichen Ansprache des Nutzers durch werbende Dritte, deren Anzeigen auf der Basis des ausgewerteten Nutzerverhalten auf dieser Website angezeigt werden. Diese Verarbeitung dient ebenfalls unserem finanziellen Interesse an der Ausschöpfung des wirtschaftlichen Potenzials unseres Internetauftritts durch entgeltliche Einblendung von personalisierten Drittwerbeinhalten.</p>
              <p>Unter der nachstehenden Internetadresse erhalten Sie weitere Informationen über die Datenschutzbestimmungen von Google: <a href="https://www.google.de/policies/privacy/">https://www.google.de/policies/privacy/</a></p>
              <p>Sie können Cookies für Anzeigenvorgaben dauerhaft deaktivieren, indem Sie diese durch eine entsprechende Einstellung Ihrer Browser-Software verhindern oder Sie können das unter folgendem Link verfügbare Browser-Plug-in herunterladen und installieren:  <a href="https://www.google.com/settings/ads/plugin?hl=de">https://www.google.com/settings/ads/plugin?hl=de</a></p>
              <p>Bitte beachten Sie, dass bestimmte Funktionen dieser Website möglicherweise nicht oder nur eingeschränkt genutzt werden können, wenn Sie die Verwendung von Cookies deaktiviert haben.</p>
              <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, befolgen Sie bitte die vorstehend geschilderte Möglichkeit zur Vornahme eines Widerspruchs.</p>
              <h6><span>10.2</span> Einsatz von Google Ads Conversion-Tracking</h6>
              <p>Diese Website nutzt das Online-Werbeprogramm "Google Ads" und im Rahmen von Google Ads das Conversion-Tracking der Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland („Google“). Wir nutzen das Angebot von Google Ads, um mit Hilfe von Werbemitteln (sogenannten Google Adwords) auf externen Webseiten auf unsere attraktiven Angebote aufmerksam zu machen. Wir können in Bezug zu den Daten der Werbekampagnen ermitteln, wie erfolgreich die einzelnen Werbemaßnahmen sind. Wir verfolgen damit das Anliegen, Ihnen Werbung anzuzeigen, die für Sie von Interesse ist, unsere Website für Sie interessanter zu gestalten und eine faire Berechnung der anfallenden Werbekosten zu erreichen.</p>
              <p>Das Cookie für Conversion-Tracking wird gesetzt, wenn ein Nutzer auf eine von Google geschaltete Ads-Anzeige klickt. Bei Cookies handelt es sich um kleine Textdateien, die auf Ihrem Endgerät abgelegt werden. Diese Cookies verlieren in der Regel nach 30 Tagen ihre Gültigkeit und dienen nicht der persönlichen Identifizierung. Besucht der Nutzer bestimmte Seiten dieser Website und ist das Cookie noch nicht abgelaufen, können Google und wir erkennen, dass der Nutzer auf die Anzeige geklickt hat und zu dieser Seite weitergeleitet wurde. Jeder Google Ads-Kunde erhält ein anderes Cookie. Cookies können somit nicht über die Websites von Google Ads-Kunden nachverfolgt werden. Die mithilfe des Conversion-Cookies eingeholten Informationen dienen dazu, Conversion-Statistiken für Google Ads-Kunden zu erstellen, die sich für Conversion-Tracking entschieden haben. Die Kunden erfahren die Gesamtanzahl der Nutzer, die auf ihre Anzeige geklickt haben und zu einer mit einem Conversion-Tracking-Tag versehenen Seite weitergeleitet wurden. Sie erhalten jedoch keine Informationen, mit denen sich Nutzer persönlich identifizieren lassen. Wenn Sie nicht am Tracking teilnehmen möchten, können Sie diese Nutzung blockieren, indem Sie das Cookie des Google Conversion-Trackings über ihren Internet-Browser unter dem Stichwort „Nutzereinstellungen“ deaktivieren. Sie werden sodann nicht in die Conversion-Tracking Statistiken aufgenommen. Wir setzen Google Ads auf Grund unseres berechtigten Interesses an einer zielgerichteten Werbung gem. Art. 6 Abs. 1 lit. f DSGVO ein. Im Rahmen der Nutzung von Google Ads kann es auch zu einer Übermittlung von personenbezogenen Daten an die Server der Google LLC. in den USA kommen.</p>
              <p>Unter der nachstehenden Internetadresse erhalten Sie weitere Informationen über die Datenschutzbestimmungen von Google: <a href="https://www.google.de/policies/privacy/">https://www.google.de/policies/privacy/</a></p>
              <p>Sie können dem Setzen von Cookies durch Google Ads Conversion-Tracking dauerhaft widersprechen, indem Sie das unter folgendem Link verfügbare Browser-Plug-in von Google herunterladen und installieren: <a href="https://www.google.com/settings/ads/plugin?hl=de">https://www.google.com/settings/ads/plugin?hl=de</a></p>
              <p>Bitte beachten Sie, dass bestimmte Funktionen dieser Website möglicherweise nicht oder nur eingeschränkt genutzt werden können, wenn Sie die Verwendung von Cookies deaktiviert haben.</p>
              <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, deaktivieren Sie diesen Dienst im auf der Webseite bereitgestellten "Cookie-Consent-Tool" oder befolgen Sie alternativ die vorstehend geschilderte Möglichkeit zur Vornahme eines Widerspruchs.</p>
              <h6><span>10.3</span>Google Marketing Platform</h6>
              <p>Diese Webseite nutzt das Online Marketing Tool Google Marketing Platform des Betreibers Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland ("GMP").</p>
              <p>GMP setzt Cookies ein, um für die Nutzer relevante Anzeigen zu schalten, die Berichte zur Kampagnenleistung zu verbessern oder um zu vermeiden, dass ein Nutzer die gleichen Anzeigen mehrmals sieht. Über eine Cookie-ID erfasst Google, welche Anzeigen in welchem Browser geschaltet werden und kann so verhindern, dass diese mehrfach angezeigt werden. Die Verarbeitung erfolgt auf Basis unseres berechtigten Interesses an der optimalen Vermarktung unserer Website gemäß Art. 6 Abs. 1 lit. f DSGVO.</p>
              <p>Darüber hinaus kann GMP mithilfe von Cookie-IDs sog. Conversions erfassen, die Bezug zu Anzeigenanfragen haben. Das ist etwa der Fall, wenn ein Nutzer eine GMP-Anzeige sieht und später bei Nutzung des gleichen Browsers die Website des Werbetreibenden aufruft und über diese Website etwas kauft. Laut Google enthalten GMP-Cookies keine personenbezogenen Informationen.</p>
              <p>Aufgrund der eingesetzten Marketing-Tools baut Ihr Browser automatisch eine direkte Verbindung mit dem Server von Google auf. Wir haben keinen Einfluss auf den Umfang und die weitere Verwendung der Daten, die durch den Einsatz dieses Tools durch Google erhoben werden und informieren Sie daher entsprechend unserem Kenntnisstand wie folgt: Durch die Einbindung von GMP erhält Google die Information, dass Sie den entsprechenden Teil unseres Internetauftritts aufgerufen oder eine Anzeige von uns angeklickt haben. Sofern Sie bei einem Dienst von Google registriert sind, kann Google den Besuch Ihrem Account zuordnen. Selbst wenn Sie nicht bei Google registriert sind bzw. sich nicht eingeloggt haben, besteht die Möglichkeit, dass der Anbieter Ihre IP-Adresse in Erfahrung bringt und speichert. Im Rahmen der Nutzung von GMP kann es auch zu einer Übermittlung von personenbezogenen Daten an die Server der Google LLC. in den USA kommen.</p>
              <p>Wenn Sie der Teilnahme an diesem Tracking-Verfahren widersprechen möchten, können Sie Cookies für Conversion-Tracking deaktivieren, indem Sie Ihren Browser so einstellen, dass Cookies von der Domain www.googleadservices.com blockiert werden, (s. https://www.google.de/settings/ads), wobei diese Einstellung gelöscht wird, wenn Sie Ihre Cookies deaktivieren. Alternativ können Sie sich bei der Digital Advertising Alliance unter der Internetadresse www.aboutads.info über das Setzen von Cookies informieren und Ihre gewünschten Einstellungen vornehmen. Schließlich können Sie Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und einzeln über deren Annahme entscheiden oder die Annahme von Cookies für bestimmte Fälle oder generell ausschließen. Bei der Nichtannahme von Cookies kann die Funktionalität unserer Website eingeschränkt sein.</p>
              <p>Unter der nachstehenden Internetadresse erhalten Sie weitere Informationen über die Datenschutzbestimmungen von GMP by Google: <a href=" https://www.google.de/policies/privacy/"> https://www.google.de/policies/privacy/</a></p>
              <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, befolgen Sie bitte die vorstehend geschilderte Möglichkeit zur Vornahme eines Widerspruchs.</p>
              <h6><span>10.4</span> Heureka Sales Tracking</h6>
              <p>Diese Website verwendet die Tracking-Technologie der Heureka Group a.s., Karolinska 650/1, 186 00, Praha 8, Tschechien („Heureka“), um bestimmte Nutzeraktionen nachzuvollziehen und auszuwerten, die nach einer Weiterleitung von „heureka.cz“ unserer Webseite durchgeführt wurden. Heureka verwendet hierfür Cookies, also kleine Textdateien, die bei Aufruf der Portale und bei Weiterleitung auf unsere Website lokal im Zwischenspeicher des Internet-Browsers des Seitenbesuchers gespeichert werden und bestimmte Browser- und Endgeräteinformationen (einschließlich der IP-Adresse, die aber sofort nach der Erhebung und vor deren Speicherung pseudonymisiert wird) an Heureka übermitteln. Durch den Einsatz der Cookies wird nutzerspezifisch registriert, ob eine abgeschlossene Bestellung auf unserer Webseite stattgefunden hat. Außerdem werden bestimmte bestellspezifische Informationen (Wert des Warenkorbs, Einzelpreise der gekauften Produkte, Produkt-SKUs, Währung) an Heureka übermittelt. Hierdurch kann der Nutzerprozess vom Aufrufen der Anzeige auf „Heureka.cz“ bis zum Bestellabschluss von uns als Ganzes nachvollzogen werden. Eine Erfassung der bestellspezifischen Informationen und deren Übermittlung an und Speicherung durch Heureka findet nur statt, wenn nach Weiterleitung auf unsere Webseite eine Bestellung tatsächlich getätigt wurde.</p>
              <p>Sofern die durch die Cookies übermittelten Informationen personenbezogene Nutzerdaten umfassen, erfolgt die Verarbeitung gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an der statistischen Auswertung des Erfolgs von Produktanzeigen auf „heureka.cz“ und des Kaufverhaltens der Nutzer und dient so der Optimierung unseres Online-Angebots.</p>
              <p>Um einer Datenerhebung und -speicherung Ihrer Besucherdaten für die Zukunft zu widersprechen, können Sie Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und einzeln über deren Annahme entscheiden oder die Annahme von Cookies für bestimmte Fälle oder generell ausschließen. Bei der Nichtannahme von Cookies kann die Funktionalität unserer Website eingeschränkt sein.</p>
              <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, befolgen Sie bitte die vorstehend geschilderte Möglichkeit zur Vornahme eines Widerspruchs.</p>
              <p>Weitergehende Informationen und die Datenschutzbestimmungen von Heureka können Sie hier einsehen: <a href="https://www.heurekashopping.cz/pro-zakazniky/podminky-pouzivani-pro-zakazniky/ochrana-soukromi">https://www.heurekashopping.cz/pro-zakazniky/podminky-pouzivani-pro-zakazniky/ochrana-soukromi</a></p>
              <h6><span>11</span> Retargeting/ Remarketing/ Empfehlungswerbung</h6>
              <h6>Google Ads Remarketing</h6>
              <p>Unsere Website nutzt die Funktionen von Google Ads Remarketing, hiermit werben wir für diese Website in den Google-Suchergebnissen, sowie auf Dritt-Websites. Anbieter ist die Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland (“Google”). Zu diesem Zweck setzt Google ein Cookie im Browser Ihres Endgeräts, welches automatisch mittels einer pseudonymen Cookie-ID und auf Grundlage der von Ihnen besuchten Seiten eine interessensbasierte Werbung ermöglicht. Die Verarbeitung erfolgt auf Basis unseres berechtigten Interesses an der optimalen Vermarktung unserer Website gemäß Art. 6 Abs. 1 lit. f DSGVO.</p>
              <p>Eine darüberhinausgehende Datenverarbeitung findet nur statt, sofern Sie gegenüber Google zugestimmt haben, dass Ihr Internet-- und App-Browserverlauf von Google mit ihrem Google-Konto verknüpft wird und Informationen aus ihrem Google-Konto zum Personalisieren von Anzeigen verwendet werden, die sie im Web betrachten. Sind sie in diesem Fall während des Seitenbesuchs unserer Webseite bei Google eingeloggt, verwendet Google Ihre Daten zusammen mit Google Analytics-Daten, um Zielgruppenlisten für geräteübergreifendes Remarketing zu erstellen und zu definieren. Dazu werden Ihre personenbezogenen Daten von Google vorübergehend mit Google Analytics-Daten verknüpft, um Zielgruppen zu bilden. Im Rahmen der Nutzung von Google Ads Remarketing kann es auch zu einer Übermittlung von personenbezogenen Daten an die Server der Google LLC. in den USA kommen.</p>
              <p>Sie können die Setzung von Cookies für Anzeigenvorgaben dauerhaft deaktivieren, indem Sie das unter folgendem Link verfügbare Browser-Plug-in herunterladen und installieren: <a href="https://www.google.com/settings/ads/onweb/">https://www.google.com/settings/ads/onweb/</a></p>
              <p>Alternativ können Sie sich bei der Digital Advertising Alliance unter der Internetadresse www.aboutads.info über das Setzen von Cookies informieren und Einstellungen hierzu vornehmen. Schließlich können Sie Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und einzeln über deren Annahme entscheiden oder die Annahme von Cookies für bestimmte Fälle oder generell ausschließen. Bei der Nichtannahme von Cookies kann die Funktionalität unserer Website eingeschränkt sein. Weitergehende Informationen und die Datenschutzbestimmungen bezüglich Werbung und Google können Sie hier einsehen: <a href="https://www.google.com/policies/technologies/ads/">https://www.google.com/policies/technologies/ads/</a></p>
              <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, befolgen Sie bitte die vorstehend geschilderte Möglichkeit zur Vornahme eines Widerspruchs.</p>
              <h6><span>12</span> Tools und Sonstiges</h6>
              <h6><span>12.1</span>  Cookie Consentt Tool</h6>
              <p>  Diese Website verwendet das Cookie-Consent-Tool der TRUENDO Technologies GmbH, Schönbrunner Straße 231, 1120 Wien, Österreich („TRUENDO“), welches technisch notwendige Cookies setzt, um Ihre Cookie-Präferenzen zu speichern. Diese Datenverarbeitung erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO auf Grundlage unseres berechtigten Interesses an der Bereitstellung eines Cookie-Zustimmungsverwaltungsdienstes für die Website-Besucher.</p>
              <h6><span>12.2</span>Google reCAPTCHA</h6>
              <p>Auf dieser Website verwenden wir auch die reCAPTCHA Funktion von Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland („Google“). Diese Funktion dient vor allem zur Unterscheidung, ob eine Eingabe durch eine natürliche Person erfolgt oder missbräuchlich durch maschinelle und automatisierte Verarbeitung erfolgt. Der Dienst umfasst den Versand der IP-Adresse und ggf. weiterer von Google für den Dienst reCAPTCHA benötigter Daten an Google und erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an der Feststellung der individuellen Eigenverantwortung im Internet und der Vermeidung von Missbrauch und Spam. Im Rahmen der Nutzung von Google reCAPTCHA kann es auch zu einer Übermittlung von personenbezogenen Daten an die Se</p>
            </div>
          </div>
        </div>
      </section>



    </>
  )
}

export default Imprint